name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }} 